/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.customer;

import db4outil.DB4OUtil;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.EcoSystem;
import model.role.CustomerRole;
import model.role.CustomerSupportRole;
import model.theater.Ticket;
import model.useraccount.UserAccount;
import model.workrequest.RefundWorkRequest;
import model.workrequest.WorkRequest;

/**
 *
 * @author arenarune
 */
public class TicketHistoryJPanel extends javax.swing.JPanel {
    EcoSystem system;
    JPanel userProcessContainer;
    UserAccount ua;
    CustomerRole cr;
    /**
     * Creates new form TicketHistoryJPanel
     */
    public TicketHistoryJPanel(JPanel userProcessContainer, EcoSystem system, UserAccount ua) {
        initComponents();
        
        this.system = system;
        this.userProcessContainer = userProcessContainer;
        this.ua = ua;
        cr = (CustomerRole) ua.getRole();
        
        populateTicketTable();
        populateRequestTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRefundStatus = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTicketHistory = new javax.swing.JTable();
        btnRequest = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));

        btnBack.setBackground(new java.awt.Color(204, 204, 255));
        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblRefundStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movie Name", "Theater", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRefundStatus);
        if (tblRefundStatus.getColumnModel().getColumnCount() > 0) {
            tblRefundStatus.getColumnModel().getColumn(0).setResizable(false);
            tblRefundStatus.getColumnModel().getColumn(1).setResizable(false);
            tblRefundStatus.getColumnModel().getColumn(2).setResizable(false);
        }

        tblTicketHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movie Name", "Theater"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblTicketHistory);
        if (tblTicketHistory.getColumnModel().getColumnCount() > 0) {
            tblTicketHistory.getColumnModel().getColumn(0).setResizable(false);
            tblTicketHistory.getColumnModel().getColumn(1).setResizable(false);
        }

        btnRequest.setBackground(new java.awt.Color(136, 197, 197));
        btnRequest.setText("Request Refund");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 51, 51));
        lblTitle.setText("Ticket History");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnBack)
                .addGap(185, 185, 185)
                .addComponent(lblTitle)
                .addGap(345, 345, 345))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(154, 154, 154))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRequest)
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblTicketHistory.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Ticket.");
            return;
        }
        
        Ticket ticket = (Ticket) tblTicketHistory.getValueAt(selectedRowIndex, 0);
        
        RefundWorkRequest rwr = CustomerSupportRole.newRefundWorkRequest();
        rwr.setSender(cr);
        rwr.setTicket(ticket);
        rwr.setStatus("Pending");
        cr.getWorkQueue().getWorkQueue().add(rwr);
        populateRequestTable();
        
        DB4OUtil.getInstance().storeSystem(system);
    }//GEN-LAST:event_btnRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequest;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblRefundStatus;
    private javax.swing.JTable tblTicketHistory;
    // End of variables declaration//GEN-END:variables

    private void populateTicketTable() {
        DefaultTableModel model = (DefaultTableModel) tblTicketHistory.getModel();
        model.setRowCount(0);
        
        for (Ticket t : cr.getTickets()) {
            Object row[] = new Object[2];
            row[0] = t;
            row[1] = t.getShow().getTheater();
            model.addRow(row);
        }
    }

    private void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) tblRefundStatus.getModel();
        model.setRowCount(0);
        
        ArrayList<RefundWorkRequest> requests = new ArrayList<RefundWorkRequest>();
        for (WorkRequest wr : cr.getWorkQueue().getWorkQueue()) {
            requests.add((RefundWorkRequest) wr);
        }
        
        for (RefundWorkRequest rwr : requests) {
            Object row[] = new Object[3];
            row[0] = rwr.getTicket().getShow().getMovie();
            row[1] = rwr.getTicket().getShow().getTheater().getName();
            row[2] = rwr.getStatus();
            model.addRow(row);
        }
    }
}
