/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.customersupport;

import db4outil.DB4OUtil;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.EcoSystem;
import model.movie.Movie;
import model.network.Network;
import model.role.CustomerRole;
import model.role.CustomerSupportRole;
import model.theater.Seat;
import model.theater.Show;
import model.theater.Theater;
import model.theater.Ticket;
import model.useraccount.UserAccount;
import model.workrequest.RefundWorkRequest;

/**
 *
 * @author arenarune
 */
public class CustomerSupportWorkAreaJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    Network network;
    UserAccount ua;
    EcoSystem system;
    /**
     * Creates new form CustomerSupportWorkAreaJPanel
     */
    public CustomerSupportWorkAreaJPanel(JPanel userProcessContainer, EcoSystem system, Network network, UserAccount ua) {
        initComponents();
        
        
        this.system = system;
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.ua = ua;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWorkRequets = new javax.swing.JTable();
        btnAccept = new javax.swing.JButton();
        btnDecline = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 51, 51));
        lblTitle.setText("Customer Support Work Area");

        btnLogout.setBackground(new java.awt.Color(204, 204, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        tblWorkRequets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Customer Name", "Movie Name", "Refund Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblWorkRequets);
        if (tblWorkRequets.getColumnModel().getColumnCount() > 0) {
            tblWorkRequets.getColumnModel().getColumn(0).setResizable(false);
            tblWorkRequets.getColumnModel().getColumn(1).setResizable(false);
            tblWorkRequets.getColumnModel().getColumn(2).setResizable(false);
        }

        btnAccept.setBackground(new java.awt.Color(204, 255, 204));
        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        btnDecline.setBackground(new java.awt.Color(255, 153, 153));
        btnDecline.setText("Decline");
        btnDecline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnLogout)
                        .addGap(185, 185, 185)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAccept)
                                .addGap(407, 407, 407)
                                .addComponent(btnDecline)))))
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(lblTitle))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccept)
                    .addComponent(btnDecline))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblWorkRequets.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a work request.");
            return;
        }
        
        RefundWorkRequest rwr = (RefundWorkRequest) tblWorkRequets.getValueAt(selectedRowIndex, 0);
        
        rwr.setStatus("Accepted");
        Ticket ticket = rwr.getTicket();
        Show show = ticket.getShow();
        Movie movie = show.getMovie();
        Theater theater = show.getTheater();
        double price = ticket.getPrice();
        for (Seat s : ticket.getSeats()) {
            s.setIsBooked(false);
        }
        
        theater.getRevenueList().put(movie, theater.getRevenueList().get(movie) - price);
        movie.setRevenue(movie.getRevenue() - price);
        CustomerRole cr = (CustomerRole) rwr.getSender();
        cr.getTickets().remove(ticket);
        theater.getTicketsSold().put(movie, theater.getTicketsSold().get(movie) - ticket.getSeats().size());
        movie.setTicketCount(movie.getTicketCount() - ticket.getSeats().size());
        CustomerSupportRole.getRefundWorkQueue().remove(rwr);
        populateTable();
        
        DB4OUtil.getInstance().storeSystem(system);
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnDeclineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclineActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblWorkRequets.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a work request.");
            return;
        }
        
        RefundWorkRequest rwr = (RefundWorkRequest) tblWorkRequets.getValueAt(selectedRowIndex, 0);
        CustomerSupportRole.getRefundWorkQueue().remove(rwr);
        rwr.setStatus("Declined");
        populateTable();
        
        DB4OUtil.getInstance().storeSystem(system);
    }//GEN-LAST:event_btnDeclineActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnDecline;
    private javax.swing.JButton btnLogout;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblWorkRequets;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblWorkRequets.getModel();
        model.setRowCount(0);
        
        for (RefundWorkRequest rwr : CustomerSupportRole.getRefundWorkQueue()) {
            Object row[] = new Object[3];
            row[0] = rwr;
            row[1] = rwr.getTicket().getShow().getMovie();
            row[2] = rwr.getTicket().getPrice();
            model.addRow(row);
        }
    }
}
