/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.admin;

import db4outil.DB4OUtil;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.EcoSystem;
import model.enterprise.Enterprise;
import model.network.Network;
import model.organization.Organization;
import model.useraccount.UserAccount;

/**
 *
 * @author navyaravuri
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    EcoSystem system;
    Network network;
    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();

        this.system = system;
        this.userProcessContainer = userProcessContainer;
        network = system.getNetworkList().get(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateUA = new javax.swing.JButton();
        btnSearchUA = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        txtSearchUA = new javax.swing.JTextField();
        btnManageUA = new javax.swing.JButton();
        lblAcc = new javax.swing.JLabel();
        btnCreateE = new javax.swing.JButton();
        btnSearchE = new javax.swing.JButton();
        txtSearchE = new javax.swing.JTextField();
        btnManageE = new javax.swing.JButton();
        lblEnterprise = new javax.swing.JLabel();
        btnCreateO = new javax.swing.JButton();
        btnSearchO = new javax.swing.JButton();
        txtSearchO = new javax.swing.JTextField();
        btnManageO = new javax.swing.JButton();
        lblOrg = new javax.swing.JLabel();
        btnCreateN = new javax.swing.JButton();
        btnSearchN = new javax.swing.JButton();
        txtSearchN = new javax.swing.JTextField();
        btnManageN = new javax.swing.JButton();
        lblNetwork = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnCreateUA.setBackground(new java.awt.Color(136, 197, 197));
        btnCreateUA.setText("Create");
        btnCreateUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUAActionPerformed(evt);
            }
        });

        btnSearchUA.setBackground(new java.awt.Color(136, 197, 197));
        btnSearchUA.setText("Search");
        btnSearchUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchUAActionPerformed(evt);
            }
        });

        lblWelcome.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(0, 51, 51));
        lblWelcome.setText("Welcome Admin!");

        btnManageUA.setBackground(new java.awt.Color(136, 197, 197));
        btnManageUA.setText("Manage");
        btnManageUA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUAActionPerformed(evt);
            }
        });

        lblAcc.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblAcc.setForeground(new java.awt.Color(0, 51, 51));
        lblAcc.setText("User Account");

        btnCreateE.setBackground(new java.awt.Color(136, 197, 197));
        btnCreateE.setText("Create");
        btnCreateE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateEActionPerformed(evt);
            }
        });

        btnSearchE.setBackground(new java.awt.Color(136, 197, 197));
        btnSearchE.setText("Search");
        btnSearchE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchEActionPerformed(evt);
            }
        });

        btnManageE.setBackground(new java.awt.Color(136, 197, 197));
        btnManageE.setText("Manage");
        btnManageE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEActionPerformed(evt);
            }
        });

        lblEnterprise.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblEnterprise.setText("Enterprise");

        btnCreateO.setBackground(new java.awt.Color(136, 197, 197));
        btnCreateO.setText("Create");
        btnCreateO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateOActionPerformed(evt);
            }
        });

        btnSearchO.setBackground(new java.awt.Color(136, 197, 197));
        btnSearchO.setText("Search");
        btnSearchO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchOActionPerformed(evt);
            }
        });

        btnManageO.setBackground(new java.awt.Color(136, 197, 197));
        btnManageO.setText("Manage");
        btnManageO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOActionPerformed(evt);
            }
        });

        lblOrg.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblOrg.setForeground(new java.awt.Color(0, 51, 51));
        lblOrg.setText("Organization");

        btnCreateN.setBackground(new java.awt.Color(136, 197, 197));
        btnCreateN.setText("Create");
        btnCreateN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNActionPerformed(evt);
            }
        });

        btnSearchN.setBackground(new java.awt.Color(136, 197, 197));
        btnSearchN.setText("Search");
        btnSearchN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchNActionPerformed(evt);
            }
        });

        btnManageN.setBackground(new java.awt.Color(136, 197, 197));
        btnManageN.setText("Manage");
        btnManageN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNActionPerformed(evt);
            }
        });

        lblNetwork.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblNetwork.setForeground(new java.awt.Color(0, 51, 51));
        lblNetwork.setText("Network");

        btnLogout.setBackground(new java.awt.Color(204, 204, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(lblWelcome)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreateE)
                        .addGap(53, 53, 53)
                        .addComponent(btnManageE)
                        .addGap(55, 55, 55)
                        .addComponent(txtSearchE, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchE))
                    .addComponent(lblEnterprise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCreateO)
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblOrg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(31, 31, 31)))
                        .addComponent(btnManageO)
                        .addGap(55, 55, 55)
                        .addComponent(txtSearchO, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchO))
                    .addComponent(lblNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCreateUA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCreateN, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnManageUA)
                            .addComponent(btnManageN))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSearchUA, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearchUA))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSearchN, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearchN)))))
                .addGap(158, 158, 158))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAcc, lblEnterprise, lblOrg});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCreateE, btnCreateN, btnCreateO, btnCreateUA, btnManageE, btnManageO, btnManageUA});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSearchE, btnSearchN, btnSearchO, btnSearchUA, txtSearchE, txtSearchO, txtSearchUA});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWelcome)
                .addGap(50, 50, 50)
                .addComponent(lblAcc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateUA)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSearchUA)
                        .addComponent(txtSearchUA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnManageUA)))
                .addGap(18, 18, 18)
                .addComponent(lblNetwork)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSearchN)
                        .addComponent(txtSearchN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnManageN))
                    .addComponent(btnCreateN))
                .addGap(18, 18, 18)
                .addComponent(lblEnterprise)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchE)
                    .addComponent(txtSearchE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageE)
                    .addComponent(btnCreateE))
                .addGap(18, 18, 18)
                .addComponent(lblOrg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateO, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSearchO)
                        .addComponent(txtSearchO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnManageO)))
                .addGap(192, 192, 192))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCreateE, btnCreateO, btnCreateUA, btnManageE, btnManageO, btnManageUA});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSearchE, btnSearchO, btnSearchUA, txtSearchE, txtSearchO, txtSearchUA});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCreateN, btnManageN, btnSearchN, txtSearchN});

    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNActionPerformed
        // TODO add your handling code here:
        CreateNetworkJPanel createNetworkJPanel = new CreateNetworkJPanel(userProcessContainer, system);
        userProcessContainer.add("createNetworkJPanel", createNetworkJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateNActionPerformed

    private void btnCreateUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUAActionPerformed
        // TODO add your handling code here:
        CreatePersonJPanel createPersonJPanel = new CreatePersonJPanel(userProcessContainer, system);
        userProcessContainer.add("createPersonJPanel", createPersonJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateUAActionPerformed

    private void btnCreateEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateEActionPerformed
        // TODO add your handling code here:
        CreateEnterpriseJPanel createEnterpriseJPanel = new CreateEnterpriseJPanel(userProcessContainer, system);
        userProcessContainer.add("createEnterpriseJPanel", createEnterpriseJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateEActionPerformed

    private void btnCreateOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateOActionPerformed
        // TODO add your handling code here:
        CreateOrganizationJPanel createOrganizationJPanel = new CreateOrganizationJPanel(userProcessContainer, system);
        userProcessContainer.add("createOrganizationJPanel", createOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateOActionPerformed

    private void btnManageUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUAActionPerformed
        // TODO add your handling code here:
        ManagePersonJPanel managePersonJPanel = new ManagePersonJPanel(userProcessContainer, system);
        userProcessContainer.add("managePersonJPanel", managePersonJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageUAActionPerformed

    private void btnManageNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNActionPerformed
        // TODO add your handling code here:
        ManageNetworkJPanel manageNetworkJPanel = new ManageNetworkJPanel(userProcessContainer, system);
        userProcessContainer.add("manageNetworkJPanel", manageNetworkJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageNActionPerformed

    private void btnManageEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseJPanel manageEnterpriseJPanel = new ManageEnterpriseJPanel(userProcessContainer, system);
        userProcessContainer.add("manageEnterpriseJPanel", manageEnterpriseJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageEActionPerformed

    private void btnManageOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOActionPerformed
        // TODO add your handling code here:
        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(userProcessContainer, system);
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageOActionPerformed

    private void btnSearchUAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchUAActionPerformed
        // TODO add your handling code here:
        String search = txtSearchUA.getText();
        if (search.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a value");
            return;
        }
        UserAccount ua = null;
        for (UserAccount u : network.getUserAccountDirectory().getUserAccountList()) {
            if (u.getUsername().equals(search)) {
                ua = u;
            }
        }
        for (UserAccount u : system.getAdminDirectory().getUserAccountList()) {
            if (u.getUsername().equals(search)) {
                ua = u;
            }
        }
        for (UserAccount u : system.getCustomerDirectory().getUserAccountList()) {
            if (u.getUsername().equals(search)) {
                ua = u;
            }
        }
        if(ua == null) {
            JOptionPane.showMessageDialog(this, "User does not exist");
        }
        ViewPersonJPanel viewPersonJPanel = new ViewPersonJPanel(userProcessContainer, system, ua);
        userProcessContainer.add("viewPersonJPanel", viewPersonJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSearchUAActionPerformed

    private void btnSearchNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchNActionPerformed
        // TODO add your handling code here:
        Network network = null;
        for (Network n : system.getNetworkList()) {
            if (n.getName().equals(txtSearchN)) {
                network = n;
            }
        }
        if (network == null) {
            JOptionPane.showMessageDialog(this, "Network does not exist");
        }
        ViewNetworkJPanel viewNetworkJPanel = new ViewNetworkJPanel(userProcessContainer, system, network);
        userProcessContainer.add("viewNetworkJPanel", viewNetworkJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSearchNActionPerformed

    private void btnSearchEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchEActionPerformed
        // TODO add your handling code here:
        Enterprise enterprise = null;
        for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (e.getName().equals(txtSearchE.getText())){
                enterprise = e;
            }
        }
        if (enterprise == null) {
            JOptionPane.showMessageDialog(this, "Enterprise does not exist");
        }
        ViewEnterpriseJPanel viewEnterpriseJPanel = new ViewEnterpriseJPanel(userProcessContainer, system, enterprise);
        userProcessContainer.add("viewEnterpriseJPanel", viewEnterpriseJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSearchEActionPerformed

    private void btnSearchOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchOActionPerformed
        // TODO add your handling code here:
        Organization organization = null;
        for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
            for (Organization o : e.getOrganizationDirectory().getOrganizationDirectory()) {
                if (o.getType().equals(txtSearchO)) {
                    organization = o;
                }
            }
        }
        if (organization == null) {
            JOptionPane.showMessageDialog(this, "Organization does not exist");
        }
        ViewOrganizationJPanel viewOrganizationJPanel = new ViewOrganizationJPanel(userProcessContainer, system, organization);
        userProcessContainer.add("viewOrganizationJPanel", viewOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSearchOActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateE;
    private javax.swing.JButton btnCreateN;
    private javax.swing.JButton btnCreateO;
    private javax.swing.JButton btnCreateUA;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageE;
    private javax.swing.JButton btnManageN;
    private javax.swing.JButton btnManageO;
    private javax.swing.JButton btnManageUA;
    private javax.swing.JButton btnSearchE;
    private javax.swing.JButton btnSearchN;
    private javax.swing.JButton btnSearchO;
    private javax.swing.JButton btnSearchUA;
    private javax.swing.JLabel lblAcc;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblNetwork;
    private javax.swing.JLabel lblOrg;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTextField txtSearchE;
    private javax.swing.JTextField txtSearchN;
    private javax.swing.JTextField txtSearchO;
    private javax.swing.JTextField txtSearchUA;
    // End of variables declaration//GEN-END:variables
}
