/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.admin;

import db4outil.DB4OUtil;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.EcoSystem;
import model.enterprise.DistributionCompany;
import model.enterprise.Enterprise;
import static model.enterprise.Enterprise.EnterpriseType.TheaterChain;
import model.enterprise.ProductionHouse;
import model.enterprise.TheaterChain;
import model.enterprise.TicketingPlatform;
import model.network.Network;
import model.organization.Organization;

/**
 *
 * @author navyaravuri
 */
public class CreateOrganizationJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    EcoSystem system;
    Network network;
    /**
     * Creates new form CreateOrganizationJPanel
     */
    public CreateOrganizationJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        
        this.system = system;
        this.userProcessContainer = userProcessContainer;
        network = system.getNetworkList().get(0);
        
        populateCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbOrganization = new javax.swing.JComboBox();
        btnBack1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnCreateOrganization = new javax.swing.JButton();

        btnBack.setText("<<< Back");

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Create Organization");

        btnBack1.setBackground(new java.awt.Color(204, 204, 255));
        btnBack1.setText("<<< Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Type of Organization:");

        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Name of Organization:");

        btnCreateOrganization.setBackground(new java.awt.Color(136, 197, 197));
        btnCreateOrganization.setText("Create");
        btnCreateOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateOrganizationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnBack1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbOrganization, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(btnCreateOrganization)))
                .addContainerGap(273, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbOrganization, jLabel2, jLabel3, txtName});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnBack1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnCreateOrganization)
                .addContainerGap(281, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmbOrganization, jLabel2, jLabel3, txtName});

    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnCreateOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateOrganizationActionPerformed
        // TODO add your handling code here:
        if (txtName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter a name");
            return;
        }
        Organization.Type type = (Organization.Type) cmbOrganization.getSelectedItem();
        if (type.equals(Organization.Type.Cast) || type.equals(Organization.Type.Director) || type.equals(Organization.Type.ScreenWriter)
                || type.equals(Organization.Type.Producer)) {
            for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (e.getEnterpriseType().equals(Enterprise.EnterpriseType.ProductionHouse)) {
                    ProductionHouse ph = (ProductionHouse) e;
                    ph.getOrganizationDirectory().createOrganization(type);
                    JOptionPane.showMessageDialog(this, "Organization Created");
                    DB4OUtil.getInstance().storeSystem(system);
                    return;
                }
            }
        }
        if (type.equals(Organization.Type.Distributor)) {
            for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (e.getEnterpriseType().equals(Enterprise.EnterpriseType.DistributionHouse)) {
                    DistributionCompany db = (DistributionCompany) e;
                    db.getOrganizationDirectory().createOrganization(type);
                    JOptionPane.showMessageDialog(this, "Organization Created");
                    DB4OUtil.getInstance().storeSystem(system);
                    return;
                }
            }
        }
        if (type.equals(Organization.Type.TheaterManager)) {
            for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (e.getEnterpriseType().equals(Enterprise.EnterpriseType.TheaterChain)) {
                    TheaterChain tc = (TheaterChain) e;
                    tc.getOrganizationDirectory().createOrganization(type);
                    JOptionPane.showMessageDialog(this, "Organization Created");
                    DB4OUtil.getInstance().storeSystem(system);
                    return;
                }
            }
        }
        if (type.equals(Organization.Type.CustomerSupport)) {
            for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (e.getEnterpriseType().equals(Enterprise.EnterpriseType.TicketingPlatform)) {
                    TicketingPlatform tp = (TicketingPlatform) e;
                    tp.getOrganizationDirectory().createOrganization(type);
                    JOptionPane.showMessageDialog(this, "Organization Created");
                    DB4OUtil.getInstance().storeSystem(system);
                    return;
                }
            }
        }
    }//GEN-LAST:event_btnCreateOrganizationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnCreateOrganization;
    private javax.swing.JComboBox cmbOrganization;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    private void populateCombo() {
        cmbOrganization.removeAllItems();
        
        for (Organization.Type type : Organization.Type.values()) {
            if (type.equals(Organization.Type.Admin) || type.equals(Organization.Type.Customer)) continue;
            cmbOrganization.addItem(type);
        }
    }
}
