/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.admin;

import db4outil.DB4OUtil;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.EcoSystem;
import model.network.Network;
import model.person.Person;
import model.useraccount.UserAccount;
import validation.EmailValidator;
import validation.PasswordValidator;
import validation.PhoneValidator;

/**
 *
 * @author navyaravuri
 */
public class ViewPersonJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount ua;
    Person p;
    Network network;
    /**
     * Creates new form ViewPersonJPanel
     */
    public ViewPersonJPanel(JPanel userProcessContainer, EcoSystem system, UserAccount ua) {
        initComponents();
        
        this.system = system;
        this.userProcessContainer = userProcessContainer;
        this.ua = ua;
        p = ua.getPerson();
        network = system.getNetworkList().get(0);
        txtAddress.setText(ua.getPerson().getAddress());
        txtEmail.setText(ua.getEmail());
        txtFirstName.setText(ua.getPerson().getFirstName());
        txtLastName.setText(ua.getPerson().getLastName());
        txtPass.setText(ua.getPassword());
        txtPhno.setText(ua.getPerson().getPhoneNumber());
        txtUsername.setText(ua.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPhone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtPhno = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        lblAddress = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));

        lblPhone.setForeground(new java.awt.Color(0, 51, 51));
        lblPhone.setText("Phone Number:");

        lblEmail.setForeground(new java.awt.Color(0, 51, 51));
        lblEmail.setText("E-mail:");

        txtUsername.setEditable(false);

        txtLastName.setEditable(false);

        txtFirstName.setEditable(false);

        txtPass.setEditable(false);

        lblUsername.setForeground(new java.awt.Color(0, 51, 51));
        lblUsername.setText("Username:");

        lblFirstName.setForeground(new java.awt.Color(0, 51, 51));
        lblFirstName.setText("First Name:");

        txtAddress.setEditable(false);

        txtPhno.setEditable(false);

        lblPassword.setForeground(new java.awt.Color(0, 51, 51));
        lblPassword.setText("Password:");

        lblLastName.setForeground(new java.awt.Color(0, 51, 51));
        lblLastName.setText("Last Name:");

        txtEmail.setEditable(false);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(136, 197, 197));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblAddress.setForeground(new java.awt.Color(0, 51, 51));
        lblAddress.setText("Address:");

        btnSave.setBackground(new java.awt.Color(136, 197, 197));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(136, 197, 197));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 51, 51));
        lblTitle.setText("View Person");

        btnBack.setBackground(new java.awt.Color(204, 204, 255));
        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnUpdate)
                                    .addGap(44, 44, 44)
                                    .addComponent(btnSave)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDelete))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblUsername)
                                        .addComponent(lblPassword))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPhno)
                                        .addComponent(txtEmail)
                                        .addComponent(txtUsername)
                                        .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(txtFirstName)
                                    .addComponent(txtLastName))))))
                .addGap(229, 229, 229))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAddress, lblFirstName, lblLastName});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblEmail, lblPassword, lblPhone, lblUsername, txtEmail, txtPass, txtPhno, txtUsername});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnBack)
                .addGap(4, 4, 4)
                .addComponent(lblTitle)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFirstName)
                    .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnSave)
                    .addComponent(btnDelete))
                .addGap(187, 187, 187))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblAddress, lblFirstName, lblLastName, txtFirstName, txtLastName});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblEmail, lblPassword, lblPhone, lblUsername, txtEmail, txtPass, txtPhno, txtUsername});

    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtAddress.setEditable(true);
        txtEmail.setEditable(true);
        txtFirstName.setEditable(true);
        txtLastName.setEditable(true);
        txtPass.setEditable(true);
        txtPhno.setEditable(true);
        txtUsername.setEditable(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String address = txtAddress.getText();
        String PhNo = txtPhno.getText();
        String email = txtEmail.getText();
        String username = txtUsername.getText();
        String password = txtPass.getText();
        
        if (!PhoneValidator.isValidPhoneNumber(PhNo)) {
            JOptionPane.showMessageDialog(this, "Please enter a valid Phone number");
            txtPhno.setText("");
            txtPass.setText("");
            return;
        }
        if (!EmailValidator.isValidEmail(email)) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email");
            txtEmail.setText("");
            txtPass.setText("");
            return;
        }
        String passwordValidationResult = PasswordValidator.validatePassword(password);
        if (!passwordValidationResult.equals("Password is valid!")) {
            JOptionPane.showMessageDialog(this, "Invalid Password: \n" + passwordValidationResult);
            txtPass.setText("");
            return;
        }
        if (!system.isUnique(username)) {
            JOptionPane.showMessageDialog(this, "Username already taken");
            txtUsername.setText("");
            txtPass.setText("");
            return;
        }
        p.setFirstName(firstName);
        p.setLastName(lastName);
        p.setAddress(address);
        p.setEmail(email);
        p.setPhoneNumber(username);
        ua.setUsername(username);
        ua.setPassword(password);
        txtAddress.setEditable(false);
        txtEmail.setEditable(false);
        txtFirstName.setEditable(false);
        txtLastName.setEditable(false);
        txtPass.setEditable(false);
        txtPhno.setEditable(false);
        txtUsername.setEditable(false);
        JOptionPane.showMessageDialog(this, "Edit Successful", "Success", JOptionPane.INFORMATION_MESSAGE);
        DB4OUtil.getInstance().storeSystem(system);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if(system.getAdminDirectory().getUserAccountList().contains(ua)) {
            system.getAdminDirectory().getUserAccountList().remove(ua);
            JOptionPane.showMessageDialog(this, "Edit Successful", "Success", JOptionPane.INFORMATION_MESSAGE);
            DB4OUtil.getInstance().storeSystem(system);
            return;
        }
        if(system.getCustomerDirectory().getUserAccountList().contains(ua)) {
            system.getCustomerDirectory().getUserAccountList().remove(ua);
            JOptionPane.showMessageDialog(this, "Edit Successful", "Success", JOptionPane.INFORMATION_MESSAGE);
            DB4OUtil.getInstance().storeSystem(system);
            return;
        }
        if(network.getUserAccountDirectory().getUserAccountList().contains(ua)) {
           network.getUserAccountDirectory().getUserAccountList().remove(ua);
           JOptionPane.showMessageDialog(this, "Edit Successful", "Success", JOptionPane.INFORMATION_MESSAGE);
           DB4OUtil.getInstance().storeSystem(system);
           return;
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtPhno;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
